# Generated by Django 4.2.26 on 2025-11-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_comment_options_alter_userpost_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='status',
        ),
    ]
