# Generated by Django 4.2.26 on 2025-11-27 13:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_userpost_excerpt_remove_userpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
