# Generated by Django 4.2.26 on 2025-12-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_userpost_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
