# Generated by Django 4.2.26 on 2025-12-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_userpost_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='pet_type',
            field=models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
