# Generated by Django 4.2.26 on 2025-12-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_userpost_pet_type_alter_userpost_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='slug',
        ),
    ]
