# Generated by Django 4.2.26 on 2025-12-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_alter_userpost_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
