# Generated by Django 4.2.26 on 2025-11-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_collaboraterequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollaborateRequest',
            new_name='FeedbackRequest',
        ),
    ]
